### PR TITLE
Retaining test filter on saving a test

### PR DESCRIPTION
**Pull request by briankip**

### CODE REVIEW

**Comment by briankip** [comment]
receive test throws an error, says `Route [TestController@index] not defined.`

**Comment by mapesa** [comment]
My mistake - line 85 should read:

`return Redirect::action('TestController@index')`

`action` and not `route`

**Comment by briankip** [comment]
True

**Comment by briankip** [comment]
I see you are filtering $tests according to the search terms although on redirect its still redirecting with $tests::All(), strange.

**Comment by briankip** [comment]
The << button hapo kwa corner in edit/enter results is doing exactly what I want, Its returning back to the same state.

**Comment by briankip** [comment]
Kumbe this thing is working. NKT

**Pull request merged**
