### PR TITLE
added resending if failed, added events, fixed logic errors

### PR DESCRIPTION
**Pull request by briankip**
* Ability  to resend tests that failed tests.
* Use of events to send results
* Logic fixes

Hard to write tests for this module. 

@mapesa review

### CODE REVIEW

**Comment by briankip** [comment]
Wait, what have I done.

**Comment by briankip** [comment]
@mapesa review, I have made a few changes as described above.

**Comment by briankip** [comment]
To DO.
- Check that on verify results are sent again.

**Comment by mapesa** [comment]
@briankip, in [SanitasInterfacer:87](https://github.com/ilabafrica/iBLIS/blob/InterfacerFixes/app/api/SanitasInterfacer.php#L87) you seem to be setting the wrong return value for `requestingClinician`. Set it to `test.requestedBy` instead of `test.testedBy`.
Otherwise the code it looks ok.

**Pull request merged**
