### PR TITLE
Inventory

### PR DESCRIPTION
**Pull request by kitsao**
@kitsao review

### CODE REVIEW

**Comment by kitsao** [comment]
1. Error in migrating tables - inventory_issues!=inventory_receipts (foreign key)
2. SQLSTATE[42S02]: Base table or view not found: 1146 Table 'iblis.inventory_labtopup' doesn't exist (SQL: select * from `inventory_labTopup` order by `date` asc)
3. You do not need Receipts and Issues on the same panel...I mean the two buttons are a bit ambiguous because, clicking either takes you to a different view. Why not have them as sub-menus?
   You could retain the inventory list though
4. SQLSTATE[42S22]: Column not found: 1054 Unknown column 'issue_date' in 'order clause' (SQL: select * from `inventory_issues` order by `issue_date` asc)
5. I doubt you need receiver's name on the form. Check and clarify location too
6. The route /inventory/store_receipts does nothing upon saving
7. The model 'inventory.php' should be 'Inventory.php' - check wiki for defined coding standards
8. getCommodities() function does the exact thing like Inventory::lists('commodity', 'id') - need to do away with it and utilize laravel eloquent ORM
9. You could include short descriptions (in comment format), what a function or variable is

10.inventoryController!=InventoryController

11.Your function naming does not adhere to the coding standards e.g. store_receipts vs storeReceipts. Also check receiptsList which could be better with listReceipts. Also check the naming of views, 
   there are mix-ups e.g. stockTakeCard then editReceipts...we thought singular naming is much better.
12.There is very little localization
13.Check your table naming e.g. in InventoryLabTopUp model, the table is inventory_labTopUp which should be in small letters
14.Check travis tests failing...check that you have created tests for the controller methods.

**Comment by briankip** [comment]
Some issues I noted

- translation for `messages.success-creating-metric`, `messages.success-updating-metric` when adding a metric, check all messages in the controller.
- if the button is for adding, say receipts put 'add/create receipt' also on issues and the other places, mettrics, commodities.

**Comment by briankip** [comment]
@ereng please review 
@Lucy-Strathmore see the changes I have done.

**Comment by briankip** [comment]
Pending: permissions and tests.

**Comment by ereng** [comment]
1. SideBar Click Supplier: `Class SupplierController does not exist`
1. Receipts Add: localisation above the panel -> `messages.labStockCardReceipts`
1. Validations
 - Issues Edit, leave **Receivers Name** empty, save: The 'issued to' field is required(should be **Receivers Name**)
 - Metrics Add, leave **Unit of Issue** empty, save: The **Name** field is required (should be **Unit of Issue**)
 - Commodity Add: Only **Name** is *required*, a number of these others should be *required*
1. Commodity Edit and Metric Edit: redirects to the same page - better it redirects to index
1. Commodity Add : **Unit Price**, **Min** and **Max Level** don't reject(validate for) non numeric values
1. Top Up Issue: why is **Issue**(Button) here not in **Issues**(Menu)
1. Top Up Issue click: `Route [inventory.labStockCard] not defined. (View: C:\xampp\htdocs\iBLIS\app\views\issue\create.blade.php)`
1. Top Up Edit: **Current Balance** doesn't show
1. SideBar Menu: **Receipts** come in to the hospital before **Issues** shouldn't it be first on the Menu...just saying(No big deal)

**Comment by briankip** [comment]
1. fixed
@lucy can you fix 2,3,4,5
6. Issue is in the topup because thats where the inventory manager issues commodities according to the top-up request from the bench.
7. fixed
 8. fixed
9. True, I forgot to do this.

**Comment by kitsao** [comment]
All seems good, just a few tweaks...
1. Redirect to index after updating - metrics, suppliers, commodities ...
2. Use of textfield vs textarea - metrics (description), supplier (physical address), commodity (description, storage requirements)...
3. View button not implemented
4. Show 'No records found' if no data in relation
5. In 'Top-up', on selecting commodity, current balance is autofilled. I think it's none of the requester's business to know the current balance for a commodity.

**Comment by Lucy-Strathmore** [comment]
@ereng fixed 2,3,4,5 @kitsao fixed 1,2,4
Remaining bit is on view button implementation.

**Comment by Piusyo** [comment]
Inventory tab is missing on the side bar.

**Pull request merged**
