### PR TITLE
switching user

### PR DESCRIPTION
**Pull request by briankip**
user switch between admin and technologist

### CODE REVIEW

**Comment by briankip** [comment]
* Should be `switch to` not login as.
* The current user is switching, from admin to external user.

**Comment by briankip** [comment]
The point is to change his permissions from `admin` to `technologist` so that he does not see too much info during normal use.

**Comment by Piusyo** [comment]
It should pick user ID No. 2 in the database which I believe should be technologist as admin

**Comment by briankip** [comment]
That is not how it should be done.

**Pull request closed without merging**
