### PR TITLE
sensitivity results to sensitivity field

### PR DESCRIPTION
**Pull request by kitsao**
Append susceptibility test results from worksheet to sensitivity textfield for sending back to sanitas.
@briankip review

### CODE REVIEW

**Comment by ereng** [comment]
- how do I reproduce this new functionality, which Test Type uses this functionality would help I guess (am a bit lost)
- this is a 'temporary fix' right since info formats for sanitas perhaps should only be in the interfacer
unless it is good to introduce it as a generic feature for blis

**Comment by kitsao** [comment]
That's ok. What I wanted you to check is whether the sensitivity field is filled with data from the sensitivity tests in the culture worksheet.
1. Create drugs or seed if not yet seeded
2. Create organism and link to drugs if not yet seeded
3. Edit test types, pick one of them, 'edit' to show culture worksheet and select possible organisms.
4. Go to the tests view, choose a test with that test type and edit it for results or enter results.
5. Check the sensitivity field if it has data once you choose an isolate and giving the susceptibility results.

**Comment by ereng** [comment]
- the sensitivity field is a bit small for the all that is appended, text area might serve better
- the arrangement of inputs needs to be re-thought (vaguely saying) - it doesn't flow
- other wise it's appending fine

**Comment by kitsao** [comment]
I get you. Since this thing is dynamic from the measures side of test types, maybe we could introduce something like Text area as measure type.

**Pull request merged**
