### PR TITLE
Quality controls

### PR DESCRIPTION
**Pull request by briankip**
Quality controls module, work in progress. @mapesa please review :joy:

### CODE REVIEW

**Comment by mapesa** [comment]
Your branch hasn't even passed the few tests we have in place.
Also please have @ereng or @kitsao review - I have a little too much on my plate right now.

**Comment by briankip** [comment]
@ereng please review.

**Comment by ereng** [comment]
Probable additions and enhancements

1. Control results can be entered but neither viewed nor edited

1. Some seed data say one for each of lots, controls and control results

1. Controls and Lot page - capitalise each word of: 'add lot' and 'add control'

1. Lang::choice for Instrument|Instruments on add control page

**Comment by briankip** [comment]
Check for results in Reports

**Comment by ereng** [comment]
The reports - on clicking  'View' the:

- iLabAfrica © 2015 is misplaced

- Localisation:**Quality Controls** changes to  **control-results-log**

**Comment by kitsao** [comment]
A thought crossed my mind; if a control test is just a normal test, how about using the test types and measures as already defined instead of having to define tests and measures. The test shall then be flagged as control and not included in the workload.This is because, controls are done to validate reagents (lots).
The lot-to-lot validation is not clear to me. If I define a control then try to enter results, the same lot number appears for different tests. Seemingly, this ought to be linked to inventory...when a lot is received, the number appears in quality control.
@ereng, your thoughts?

**Comment by briankip** [comment]
@kitsao review.

**Comment by kitsao** [comment]
Undefined variable: ans  
is thrown upon attempting to save a control result.

     Call to a member function getRangeUnit() on a non-object
thrown on viewing QC report.
I also think it would be much better if the report loaded with all available data for the dates before filtering per control.
Localization is okay and footer fix is good too.

**Pull request merged**
