### PR TITLE
moh 706 report

### PR DESCRIPTION
**Pull request by kitsao**
@Piusyo , review
More details and refinements shall come in subsequent updates as data becomes cleaner.

### CODE REVIEW

**Comment by Piusyo** [comment]
All test are good both local and online.
The report still potrays same problems as others, taking long to load or failing to load with big chunks of data.
Generally Good!

**Comment by briankip** [comment]
We will need to see how we can remove the hard-coded items and move them to worksheets or something.

**Comment by briankip** [comment]
use the configs to display the hospital name.

**Comment by briankip** [comment]
Also I think this report will not work in Kapsabet, as the tests are hard coded. I think we should merge this branch to BDH alone. Thoughts.

**Comment by kitsao** [comment]
Yeah, I saw that, I'm fixing it now. Hope for the best.

**Comment by briankip** [comment]
@kitsao  Check this and see if it works on clean install without errors

**Pull request merged**
