### PR TITLE
Audit results

### PR DESCRIPTION
**Pull request by briankip**
Functionality to enable a user to be able to view previous results, when they were entered and who entered them.

The link to the report is found in the edit button. @kitsao please review

### CODE REVIEW

**Comment by kitsao** [comment]
Using an instance of the production db throws the following exception
```
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Call to a member function allowProbativeResults() on a non-object
```

**Comment by briankip** [comment]
That is not related to audit feature, what did you click. Give more details

**Comment by kitsao** [comment]
Works fine. 
Will the inclusion of navigation buttons on the view make it better? 
The sidebar collapses upon opening the audit report.

**Comment by briankip** [comment]
@kitsao how does it look now

**Comment by kitsao** [comment]
Looks good.

**Pull request merged**
