### PR TITLE
Move measures to test type view

### PR DESCRIPTION
**Pull request by ereng**
@mapesa please review

### CODE REVIEW

**Comment by mapesa** [comment]
1. "Add Range" button is displayed even for measures of type FREE_TEXT
1. While entering results, interpretations are over-written (*I think you had fixed this in the master*)
1. I find the unit/functional tests wanting, but that is a general critic of the current blis rather than of this branch.

Even with these glitches it looks good enough to merge. Ascertain that point 2 above is sorted when merging.

**Comment by ereng** [comment]
Will first merge master into non-reusable-measures and see

**Comment by ereng** [comment]
All good am merging

**Comment by briankip** [comment]
- Whats the description for?
- Design skills = 0 :joy: :joy:  :joy: :joy:

**Comment by ereng** [comment]
let dem...

**Comment by briankip** [comment]
- Can't edit alphanumeric values!!

**Comment by ereng** [comment]
Check your environment, working directory...etc, coz it's working...

**Pull request merged**
